###
// create study spot template
POST http://localhost:3001/studyspots/create
Content-Type: application/json

{
    "spotId": 6,
    "name": "Library@Esplanade",
    "description": "Libraries are generally good places to study — as long as you can find a seat. Library@esplanade is one of the least crowded libraries, so you’ll easily be able to secure a spot. Located centrally in town, the library is in a fairly convenient location, but not near any schools and therefore not as often frequented by students. It’s got a conducive environment, great views, and plenty of seats, which makes it one of the best libraries to study in.",
    "picturePath": "https://confirmgood.com/wp-content/uploads/2022/07/4_places-to-study.png",
    "misc": {
        "freeWifi": "Available",
        "freeSeating": "Available",
        "openingHours": {
            "weekdays": "11am - 9pm",
            "weekends": "11am - 9pm"
        }, 
        "phoneNumber": "Not available",
        "websiteURL": "https://www.nlb.gov.sg/main/home"
    },
    "location": {
        "address": "8 Raffles Ave., #03-01, Singapore",
        "postal": "039802",
        "type": "Point",
        "coordinates" : [
            1.290005906820569, 103.85574823207673
        ]
    }
}

###
// create another study spot 
POST http://localhost:3001/studyspots/create
Content-Type: application/json

{
    "spotId": 4,
    "name": "Lowercase Cafe",
    "description": "Free wifi provided. Located in LASELLE College of Arts. Hours: Mon to Sat 8AM to 8PM. The quieter ambience and the school-like atmosphere are a couple of clear distinctions. But most of all is its unique architecture that allows an abundance of sunlight to pass during the day.",
    "picturePath": "https://lh3.googleusercontent.com/p/AF1QipMW83dUN0c0HHCoPwiXKOcdzZiY44WyKTMbkX6S=s680-w680-h510",
    "location": {
        "address": "Blk D #01-01, 1 McNally St",
        "postal":  187940,
        "type": "Point",
        "coordinates" : [
            1.3028283326926806, 103.85202617273396
        ]
    }
}

###
// create another study spot 
POST http://localhost:3001/studyspots/create
Content-Type: application/json

{
    "spotId": 1,
    "name": "The Book Cafe",
    "description": "As the name suggests, The Book Cafe is more likely designed for the book worms. A go-to study cafe in Singapore where you can catch the positive vibes to study or work.",
    "picturePath": "https://lh3.googleusercontent.com/p/AF1QipOqRA4mUSostbDEWT4LNm-ooS5thK3hf9U-NHsk=s680-w680-h510",
    "location": {
        "address": "20 Martin Rd, #01-02 Seng Kee Building, Singapore",
        "postal": 239070,
        "type": "Point",
        "coordinates" : [
            1.2912729566797299, 103.83907758163993
        ]
    }
}

### 

// get all study spots
GET http://localhost:3001/studyspots/

###

// get study spot by id
GET http://localhost:3001/studyspots/641408f9b4b8c89c10e2f0e4

###

// create user
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "test",
    "email": "test1@test.com",
    "password": "test",
    "picturePath": ""
}

###

// get user by id
GET http://localhost:3001/users/641e817758326ac9e3d0b462

###

// add studyspot to user favourites
PATCH http://localhost:3001/studyspots/641ec77dfa85327b95899bb9/641e817758326ac9e3d0b462

###

// get user favourite spots
GET http://localhost:3001/users/641e817758326ac9e3d0b462/favorite-spots

###

// get user reviews
GET http://localhost:3001/users/641e817758326ac9e3d0b462/reviews

### 

POST http://localhost:3001/studyspots/641ec693fa85327b95899bb6/reviews
Content-Type: application/json

{
    "userId": "641e817758326ac9e3d0b462",
    "rating": 5,
    "comment": "daaaa"
}